Tx detail layout
thorchain/asgardex-electron pull request #1095
Opened 2021-03-12 13:38 UTC by thatStrangeGuyThorchain

Added UI components and stories for them:
- `TxType`
- `TxDetail`
as a part of #1017

2021-03-12 13:40 UTC, thatStrangeGuyThorchain commented on src/renderer/services/midgard/types.ts
> +export type HistoryActionsPageLD = LiveData<ApiError, HistoryActionsPage>
needed for next PR. forgot to remove from this one. pls do not pay attention here

2021-03-12 17:11 UTC, veado requested changes
LGTM! Just few suggestions...

2021-03-12 17:11 UTC, veado commented on src/renderer/components/uielements/txType/TxType.tsx
> +    default:
```
default: return <></> // (no icon)
```

2021-03-12 17:11 UTC, veado commented on src/renderer/components/uielements/txType/TxType.tsx
> +    case TxTypes.DOUBLE_SWAP:
```
return <SwapIcon />
```

2021-03-12 17:11 UTC, veado commented on src/renderer/components/uielements/txType/TxType.tsx
> +      return 'common.tx.type.swap'
return '' as default

2021-03-12 17:11 UTC, veado commented on src/renderer/i18n/de/common.ts
> +  'common.tx.type.withdraw': 'Withdraw - DE'
'common.tx.type.swap': 'Swap', // as same as `common.swap`
  'common.tx.type.doubleSwap': 'Doppel Swap',
  'common.tx.type.deposit': 'Einzahlen', // similar to `common.add`
  'common.tx.type.withdraw': 'Auszahlen'

2021-03-12 17:11 UTC, veado commented on src/renderer/types/asgardex.ts
> +export type HistoryActions = HistoryAction[]
Let's move these types into `services/midgard/types.ts` or into `types/history`

2021-03-13 12:44 UTC, thatStrangeGuyThorchain commented on src/renderer/components/uielements/txDetail/TxDetail.styles.ts
> +  font-size: 0.75rem;
hmmm. just an old habit 😅 _will change to pixels_

2021-03-13 20:45 UTC, veado approved these changes

2021-03-14 18:03 UTC, merged