Fix decimal handling of ETH/ERC20 for deposit
thorchain/asgardex-electron pull request #1116
Opened 2021-03-16 19:43 UTC by veado

- [x] Fix decimal handling of ETH/ERC20 for deposit
- [x] Add `convertDecimalFromMidgard`
- [ ] Test `convertDecimalFromMidgard`

2021-03-16 19:50 UTC, veado commented on src/renderer/helpers/assetHelper.ts
> +export const convertDecimalFromMidgard = (amount: BigNumber, decimal: number): BigNumber => {
^ change function to
```ts
(amount: BaseAmount) => BaseAmount
```

2021-03-16 19:50 UTC, veado commented on src/renderer/helpers/assetHelper.ts
> + * ETH.ETH: Midgard 1e8 vs. ETH 1e18
```
Example ETH.ETH: 
- Midgard 1e8 decimal (for any asset)
- ETH 1e18 decimal

In this case `convertDecimalFromMidgard` converts amount from 1e8 to 1e18 decimal
```

2021-03-18 00:57 UTC, sarawut11 commented on src/renderer/components/swap/Swap.tsx
> +        const assetPoolData: PoolData | undefined = poolsData[assetToString(asset)]
We can use `O.fromNullable` with FP

2021-03-18 00:58 UTC, sarawut11 requested changes
looks good to me, just small comment

2021-03-18 09:32 UTC, junkai121 approved these changes
LGTM!

2021-03-18 13:34 UTC, sarawut11 approved these changes
LGTM!

2021-03-18 13:43 UTC, merged