Add missing menu for FR
thorchain/asgardex-electron pull request #1227
Opened 2021-03-29 15:47 UTC by veado

Fixes #1221

2021-03-29 17:23 UTC, Weyland2093 commented
import { EditMenuMessages, HelpMenuMessages, ViewMenuMessages, AppMenuMessages } from '../types'

const appMenu: AppMenuMessages = {
  'menu.app.about': 'À propos de {name}',
  'menu.app.hideApp': 'Masquer {name}',
  'menu.app.hideOthers': 'Masquer les autres',
  'menu.app.unhide': 'Montrer tout',
  'menu.app.quit': 'Quitter {name}'
}

const editMenu: EditMenuMessages = {
  'menu.edit.title': 'Edition',
  'menu.edit.undo': 'Annuler',
  'menu.edit.redo': 'Rétablir',
  'menu.edit.cut': 'Couper',
  'menu.edit.copy': 'Copier',
  'menu.edit.paste': 'Coller',
  'menu.edit.selectAll': 'Sélectionner tout'
}

const helpMenu: HelpMenuMessages = {
  'menu.help.title': 'Aide',
  'menu.help.learn': 'En apprendre davantage...',
  'menu.help.docs': 'Documentation',
  'menu.help.telegram': 'Telegram',
  'menu.help.issues': 'Signaler les problèmes'
}

const viewMenu: ViewMenuMessages = {
  'menu.view.title': 'Affichage',
  'menu.view.reload': 'Recharger',
  'menu.view.toggleFullscreen': 'Basculer en plein écran',
  'menu.view.toggleDevTools': 'Basculer en outils de dev.'
}

export default { ...appMenu, ...editMenu, ...viewMenu, ...helpMenu }

2021-03-30 11:29 UTC, mcadam requested changes

2021-03-30 11:29 UTC, mcadam commented on src/main/i18n/fr/index.ts
> +  'menu.view.toggleDevTools': 'Basculer en outils de dev.'
"Basculer en outils de développement"

2021-03-30 11:29 UTC, mcadam commented on src/main/i18n/fr/index.ts
> +  'menu.help.issues': 'Signaler les problèmes'
Signaler un problème

2021-03-30 17:34 UTC, merged