Show details within tiles on the top
thorchain/asgardex-electron pull request #1244
Opened 2021-03-31 17:42 UTC by junkai121

close #1234

2021-03-31 18:03 UTC, veado requested changes

2021-03-31 18:03 UTC, veado commented on src/renderer/i18n/en/deposit.ts
> +  'deposit.poolDetails.apy': 'APY',
It seems we have some some of translations at other places as well (e.g. `Liquidity`, `Earnings`, `Fees` etc.). If so, pls extract duplications to `common.xyz`

2021-04-01 15:30 UTC, thatStrangeGuyThorchain commented on src/renderer/services/midgard/pools.ts
> +    RxOp.switchMap(([oSelectedPoolAsset, delay]) =>
actually.... you are the person who had added it 😅 delay needed for Deposit views to reload pool's data after any Depoist/withdraw actions after 5 secs

2021-04-01 16:13 UTC, veado commented on src/renderer/services/midgard/pools.ts
> +    RxOp.switchMap(([oSelectedPoolAsset, delay]) =>
If I remember correctly, in _Deposit_ we do need it for re-loading shares after sending deposit tx. However, we don't need it here and can just ignore handling of `delay`.

2021-04-01 17:17 UTC, thatStrangeGuyThorchain commented on src/renderer/services/midgard/pools.ts
> +    RxOp.switchMap(([oSelectedPoolAsset, delay]) =>
👌

2021-04-01 17:48 UTC, veado submitted a review, later dismissed

2021-04-01 18:07 UTC, merged