Resolve: Update to latest xchain-binance
thorchain/asgardex-electron pull request #1728
Opened 2021-09-03 11:50 UTC by gromxyz

Check:
- [x] SWAP
- [ ] ADD
- [ ] WITHDRAW
- [ ] SEND
- [ ] Tx history

Closes #1725

2021-09-03 13:11 UTC, veado approved these changes

2021-09-03 13:14 UTC, veado requested changes
`@binance-chain/javascript-sdk` needs to be bumped, too.

- `4.2.0` https://github.com/xchainjs/xchainjs-lib/blob/master/packages/xchain-binance/package.json#L46
- Currently  `4.1.1` `https://github.com/thorchain/asgardex-electron/blob/57b0493c45a429e6a82b468653d251ef1490dded/package.json#L64`

2021-09-03 15:57 UTC, veado approved these changes

2021-09-03 15:58 UTC, merged

2021-09-14 06:22 UTC, Knowledge231 reviewed
Good

2021-09-14 06:22 UTC, Knowledge231 commented on package.json
> -    "@xchainjs/xchain-binance": "^5.3.0",
Cool

2021-09-14 06:22 UTC, Knowledge231 commented on package.json
> -    "@xchainjs/xchain-binance": "^5.3.0",
😁