[WIP] Sign BNB transactions using Ledger
thorchain/asgardex-electron pull request #1782
Opened 2021-09-20 15:04 UTC by gromxyz

Closes #1772

2021-09-21 13:16 UTC, veado requested changes
Nice! Just few (small) things ...

2021-09-21 13:16 UTC, veado commented on src/renderer/services/binance/transaction.ts
> +      sender: params.sender ? params.sender : '',
```ts
sender: params.sender
```

2021-09-21 13:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +        msg: `Post request to send 'MsgSend' failed`
```ts
`Post request to send ${asset?.symbol ?? AssetBNB.symbol} transaction by using Ledger failed`
```

2021-09-21 13:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +        msg: `Binance client failed to send transaction`
```
Binance client failed to send transaction using Ledger
```

2021-09-21 13:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +    if (result.length === 0 || result[0].hash === undefined) {
```
result.length === 0 || !result[0].hash
```

2021-09-21 13:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +        msg: `Getting sender address failed`
`Getting sender address using Ledger failed`

2021-09-21 13:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +      asset ? asset.symbol : AssetBNB.symbol,
```ts
asset?.symbol ?? AssetBNB.symbol
```

2021-09-21 13:16 UTC, veado commented on src/renderer/services/binance/transaction.ts
> +                  msg: `Sending Ledger BNB tx failed. (${msg})`
```ts
Sending Ledger ${asset?.symbol ?? AssetBNB.symbol} tx failed. (${msg})
```

2021-09-21 13:16 UTC, veado commented on src/renderer/services/thorchain/transaction.ts
> +      sender: params.sender ? params.sender : '',
```ts
sender: params.sender
```

2021-09-21 16:24 UTC, veado approved these changes, later dismissed
:+1:

2021-09-21 18:01 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> +    await app.showAddress(prefix, derivePath)
Do we really need this call of `showAddress`^? By calling `useLedgerSigningDelegate` Binance app on Ledger is showing address + txs address as well

2021-09-21 18:09 UTC, gromxyz commented on src/main/api/ledger/binance/transaction.ts
> +    await app.showAddress(prefix, derivePath)
Good catch, removing it 👍

2021-09-21 18:16 UTC, veado commented on src/main/api/ledger/binance/transaction.ts
> + */
typo `Sends Binance tx using Ledger`

2021-09-22 18:11 UTC, veado approved these changes

2021-09-23 10:13 UTC, merged