import keystore feature
thorchain/asgardex-electron pull request #758
Opened 2021-01-14 16:06 UTC by sarawut11

2021-01-14 18:02 UTC, veado requested changes

2021-01-15 03:36 UTC, sarawut11 commented on src/renderer/components/wallet/keystore/Keystore.styles.tsx
> +  color: #4a5564;
I can't find same color in the themes. Can you share the file link you mentioned?

2021-01-18 15:13 UTC, veado requested changes

2021-01-18 15:13 UTC, veado commented on src/renderer/components/wallet/keystore/Keystore.styles.tsx
> +  color: #4a5564;
Is this a color defined in [our Figma layouts](https://www.figma.com/file/LgRqZCGMShZ2mJ702MIqyV/ASGARDEX-2020)?

2021-01-18 15:13 UTC, veado commented on src/renderer/i18n/de/wallet.ts
> +  'wallet.imports.error.keystore.import': 'Error while importing keystore - DE',
```
  'wallet.imports.error.instance': 'Es konnte keine Instanz vom Client erstellt werden',
  'wallet.imports.error.keystore.load': 'Fehler beim Laden der Keystore-Datei',
  'wallet.imports.error.keystore.import': 'Fehler beim Importieren der Keystore-Datei',
```

2021-01-18 15:13 UTC, veado commented on src/renderer/components/wallet/keystore/ImportKeystore.tsx
> +  const [importError, setImportError] = useState<O.Option<Error>>(O.none)
By using and subscribing to `importKeystore$` and `loadKeystore$`, we can store it's value (which is RemoteData) into a state. This state includes `pending`, `failure` and `success`. That's we can remove extra state handling of `importing`, `importError`.

To get an idea, check `Swap.tsx` component, where we deal with a value of `RemoteData` by subscribing to `swap$`. It's not the same stream or `RemoteData` here in ImportKeystore` we have to deal with, but the same idea behind.

2021-01-18 16:54 UTC, veado submitted a review, later dismissed
:+1:

2021-01-18 19:17 UTC, veado approved these changes

2021-01-18 19:17 UTC, veado commented on src/renderer/components/wallet/keystore/Keystore.styles.tsx
> +
Do we still need these lines ^?

2021-01-19 09:34 UTC, merged