WIP: Refactor data handling for pool shares
thorchain/asgardex-electron pull request #859
Opened 2021-02-05 19:55 UTC by veado

2021-02-06 20:47 UTC, sarawut11 submitted a review, later dismissed
Nice!

2021-02-08 09:00 UTC, thatStrangeGuyThorchain requested changes

2021-02-08 10:22 UTC, veado commented on src/renderer/components/currency/CurrencyInfo.tsx
> +              amount: assetAmount(1),
`ONE_ASSET_AMOUNT` based on `decimal=8` and we can't use it anywhere. Running `assetAmount(1)` has (almost) no cost. Why do you think calling a function with a constant `1` will re-render the component?

2021-02-08 10:25 UTC, veado commented on src/renderer/views/deposit/withdraw/WithdrawDepositView.tsx
> +  const _chainAssetPoolDataRD: RD.RemoteData<Error, PoolData> = FP.pipe(
Good catch! It can be removed, we don't need this data anymore. Same with `_assetPoolDataRD`.

2021-02-08 10:47 UTC, veado commented on src/renderer/services/midgard/utils.ts
> +export const combineShares = (shares: PoolShares): PoolShares =>
Description seems to be misleading: Given `PoolShares` includes `Poolshare` items, which might be based on different assets (not just a same asset). Check out [test for `combineShares`](https://github.com/thorchain/asgardex-electron/pull/859/files#diff-7ea606df48c38c08df1859d36f7a36dfee70bd55d91ed6297559f85272be297fR313-R338) to see data structure of given `Poolshares` and returning `PoolShares`. Both are list of `PoolShare` items. _I'm going to update the description..._

2021-02-08 11:42 UTC, merged